### ISSUE TITLE
City not populated

### ISSUE THREAD

**Issue by jagmann1** [a33ik/GoogleAddressAutocomplete_PCF#1]
I search for an address in Norway "Stanseveien 16", selecting that address, and then all fields except the city is populated.

However if i search for and address in New York, the city is populated
[PCF.docx](https://github.com/a33ik/GoogleAddressAutocomplete_PCF/files/3461387/PCF.docx)

Please see attachments with screenshots of the custom control configuration

**Comment by a33ik** [comment]
Thanks for the report. Fix is on the way.
Andrew

**Comment by a33ik** [comment]
Should be fixed now - https://github.com/a33ik/GoogleAddressAutocomplete_PCF/releases/tag/1.0.0.1
