### ISSUE TITLE
Namespace google not found

### ISSUE THREAD

**Issue by yuvalrs** [a33ik/GoogleAddressAutocomplete_PCF#2]
When trying 'npm run build' the build fails.
The following errors are displayed:
C:\_Work\_PCF\Projects\AddressAutocomplete>npm run build

> pcf-project@1.0.0 build C:\_Work\_PCF\Projects\AddressAutocomplete
> pcf-scripts build

[17:21:27] [build]  Initializing...
[17:21:27] [build]  Validating manifest...
[17:21:27] [build]  Validating control...
[17:21:28] [build]  Generating manifest types...
[17:21:28] [build]  Compiling and bundling control...
[Webpack stats]:
Hash: 2b71d3614e44a4688af0
Version: webpack 4.28.4
Time: 2456ms
Built at: 08/04/2019 5:21:31 PM
    Asset      Size  Chunks             Chunk Names
bundle.js  8.92 KiB    main  [emitted]  main
Entrypoint main = bundle.js
[./AddressAutocomplete/index.ts] 4.73 KiB {main} [built] [2 errors]

ERROR in C:\_Work\_PCF\Projects\AddressAutocomplete\AddressAutocomplete\index.ts
./AddressAutocomplete/index.ts
[tsl] ERROR in C:\_Work\_PCF\Projects\AddressAutocomplete\AddressAutocomplete\index.ts(8,27)
      TS2503: ****Cannot find namespace 'google**'**.

ERROR in C:\_Work\_PCF\Projects\AddressAutocomplete\AddressAutocomplete\index.ts
./AddressAutocomplete/index.ts
[tsl] ERROR in C:\_Work\_PCF\Projects\AddressAutocomplete\AddressAutocomplete\index.ts(50,37)
      TS2304: **Cannot find name 'google'.**
[17:21:31] [build]  Failed:
[pcf-1033] [Error] An error occurred compiling or bundling the control.

**Comment by a33ik** [comment]
Try to run following command that installs required types - npm install --save @types/googlemaps
Source - https://www.npmjs.com/package/@types/googlemaps

**Comment by a33ik** [comment]
Closing the issue.
