### ISSUE TITLE
Error while importing the solution

### ISSUE THREAD

**Issue by RavitejaMuthyala** [a33ik/GoogleAddressAutocomplete_PCF#3]
I tried to install your solution into our Dynamics but it errored out. Need some assistance to use this in Dynamics

  | The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.
-- | --

**Comment by onyebuchiboss** [comment]
@RavitejaMuthyala u can rebuild it yourself.

**Comment by a33ik** [comment]
@RavitejaMuthyala I can't reproduce your issue. What's the version of the instance you try to import solution to? Is it online or on-premise?

**Comment by a33ik** [comment]
@RavitejaMuthyala closing the thread.

**Comment by RavitejaMuthyala** [comment]
@a33ik Version 1710 (9.1.0.8428) online. still won't import directly. Guess will rebuild it myself

**Comment by a33ik** [comment]
@RavitejaMuthyala do you download this file - https://github.com/a33ik/GoogleAddressAutocomplete_PCF/releases/download/1.0.0.1/GoogleAddressAutocomplete_1_0_0_1_managed.zip ?

**Comment by RavitejaMuthyala** [comment]
this one worked, thank you

**Comment by a33ik** [comment]
@RavitejaMuthyala awesome! Glad that it worked!
