### ISSUE TITLE
OOB Address fields like Address1:Line1, Address:City not coming while mapping the fields

### ISSUE THREAD

**Issue by bipinshan** [a33ik/GoogleAddressAutocomplete_PCF#4]
Hi, 

I am trying to use this feature on Lead entity. I have created custom field to add this control. While mapping the address fields like Street, City, country etc i do not see OOB Single Line fields like Address1:Line1, Address:City in dropdown fields.

Thanks,
bipin

**Comment by a33ik** [comment]
Hello,
This is a bug of PCF and Microsoft aware of it. Here is the work around - https://www.magnetismsolutions.com/blog/jaredjohnson/2019/07/04/binding-to-address-fields-in-a-pcf-control
Andrew

**Comment by bipinshan** [comment]
Thank you !

**Comment by bipinshan** [comment]
Hey,

Even though i have mapped OOB fields using method explained by magnetismsolution to update formxml. Address is not getting populated successfully. [
![google address auto complete](https://user-images.githubusercontent.com/3380476/65757458-ccadc500-e134-11e9-8147-1fc951a68169.png)
](url)

Please assist.
