### ISSUE TITLE
Address is not getting populated successfully after mapping of field using formxml

### ISSUE THREAD

**Issue by bipinshan** [a33ik/GoogleAddressAutocomplete_PCF#5]
Hello,
This is a bug of PCF and Microsoft aware of it. Here is the work around - https://www.magnetismsolutions.com/blog/jaredjohnson/2019/07/04/binding-to-address-fields-in-a-pcf-control
Andrew

Hey,

Even though i have mapped OOB fields using method explained by magnetismsolution to update formxml. Address is not getting populated successfully.

![google address auto complete](https://user-images.githubusercontent.com/3380476/65761958-8872f280-e13d-11e9-93c2-8c069a09cf1e.png)

As you can see in above screenshot, we have mapped with OOB address fields. But when I tried from UI value is auto populating.

You can also verify this in any trial instance.

Please assist.

**Comment by a33ik** [comment]
Hello,
Can you please post a screenshot that describes how it looks like in environment?
Andrew

**Comment by bipinshan** [comment]
When we modified FormXML directly by exporting solution and making changes in Customization.xml file then importing it back to instance, It was not working.

However, When I tried modifying the FormXML using XRM ToolBox plugin, It started working.

Thank you!
